---
name: concourse
director_uuid: {{ director_uuid }}

releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

variables:
- name: atc_db_password
  type: password
- name: atc_user_password
  type: password
- name: concourse_ca
  type: certificate
  options:
    is_ca: true
    common_name: Concourse CA
- name: concourse_tls
  type: certificate
  options:
    ca: concourse_ca
    common_name: {{ poolIP0 }}
    alternative_names:
      - concourse.{{ poolIP0 }}.cf.pcfazure.com
      - {{ poolIP0 }}
      - 127.0.0.1

instance_groups:
- name: db
  instances: 1

  vm_type: Standard_DS2_v2
  stemcell: trusty
  persistent_disk_type: 5120
  networks:
    - name: boshvnet
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: &atc_db atc
        role: atc
        password: ((atc_db_password))
  update:
    serial: true

- name: web
  instances: 1
  vm_type: Standard_DS2_v2
  stemcell: trusty
  networks:
    - name: vip
      static_ips: [{{ poolIP0 }}]
    - name: boshvnet
      default: [dns, gateway]
  jobs:

  - name: atc
    release: concourse
    properties:

      bind_port: 80
      tls_bind_port: 443

      # replace with your CI's externally reachable URL, e.g. https://ci.foo.com
      external_url: https://concourse.{{ poolIP0 }}.cf.pcfazure.com

      # replace with username/password, or configure GitHub auth
      basic_auth_username: atc
      basic_auth_password: ((atc_user_password))

      # replace with your SSL cert and key
      tls_cert: ((concourse_tls.certificate))
      tls_key: ((concourse_tls.private_key))

      postgresql_database: *atc_db
  - name: tsa
    release: concourse
    properties: {}


- name: worker
  instances: 4
  vm_type: Standard_DS4_v2
  stemcell: trusty
  networks:
    - name: boshvnet
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
